#############################################################################
# Makefile for building: qtknots
# Generated by qmake (2.01a) (Qt 4.7.1) on: Sat Dec 18 22:00:19 2010
# Project:  qtknots.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/andy/QtSDK/QtCreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DECLARATIVE_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Iqmlapplicationviewer -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lglib-2.0 -L/lib -ldbus-1 -lrt -lQtDeclarative -lQtXml -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		knots.cpp \
		profile.cpp \
		saxprofilehandler.cpp \
		knotsdeclarative.cpp \
		mainwindow.cpp \
		knotsplayerproperties.cpp \
		knotsplayer.cpp \
		knotsitem.cpp \
		knotsdirectory.cpp \
		saxknotsitemhandler.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp \
		moc_knots.cpp \
		moc_profile.cpp \
		moc_knotsdeclarative.cpp \
		moc_mainwindow.cpp \
		moc_knotsplayerproperties.cpp \
		moc_knotsplayer.cpp \
		moc_knotsitem.cpp \
		moc_knotsdirectory.cpp \
		qrc_qtknots.cpp
OBJECTS       = main.o \
		knots.o \
		profile.o \
		saxprofilehandler.o \
		knotsdeclarative.o \
		mainwindow.o \
		knotsplayerproperties.o \
		knotsplayer.o \
		knotsitem.o \
		knotsdirectory.o \
		saxknotsitemhandler.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o \
		moc_knots.o \
		moc_profile.o \
		moc_knotsdeclarative.o \
		moc_mainwindow.o \
		moc_knotsplayerproperties.o \
		moc_knotsplayer.o \
		moc_knotsitem.o \
		moc_knotsdirectory.o \
		qrc_qtknots.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtknots.pro
QMAKE_TARGET  = qtknots
DESTDIR       = 
TARGET        = qtknots

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtknots.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/andy/QtSDK/QtCreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/andy/QtSDK/QtCreator/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtknots1.0.0 || $(MKDIR) .tmp/qtknots1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtknots1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h knots.h profile.h saxprofilehandler.h knotsdeclarative.h mainwindow.h knotsplayerproperties.h knotsplayer.h knotsitem.h knotsdirectory.h saxknotsitemhandler.h .tmp/qtknots1.0.0/ && $(COPY_FILE) --parents qtknots.qrc .tmp/qtknots1.0.0/ && $(COPY_FILE) --parents main.cpp knots.cpp profile.cpp saxprofilehandler.cpp knotsdeclarative.cpp mainwindow.cpp knotsplayerproperties.cpp knotsplayer.cpp knotsitem.cpp knotsdirectory.cpp saxknotsitemhandler.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/qtknots1.0.0/ && (cd `dirname .tmp/qtknots1.0.0` && $(TAR) qtknots1.0.0.tar qtknots1.0.0 && $(COMPRESS) qtknots1.0.0.tar) && $(MOVE) `dirname .tmp/qtknots1.0.0`/qtknots1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtknots1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp moc_knots.cpp moc_profile.cpp moc_knotsdeclarative.cpp moc_mainwindow.cpp moc_knotsplayerproperties.cpp moc_knotsplayer.cpp moc_knotsitem.cpp moc_knotsdirectory.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp moc_knots.cpp moc_profile.cpp moc_knotsdeclarative.cpp moc_mainwindow.cpp moc_knotsplayerproperties.cpp moc_knotsplayer.cpp moc_knotsitem.cpp moc_knotsdirectory.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

moc_knots.cpp: profile.h \
		mainwindow.h \
		knotsplayer.h \
		knots.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knots.h -o moc_knots.cpp

moc_profile.cpp: profile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) profile.h -o moc_profile.cpp

moc_knotsdeclarative.cpp: profile.h \
		knotsdirectory.h \
		knotsitem.h \
		saxknotsitemhandler.h \
		knotsplayerproperties.h \
		knotsdeclarative.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knotsdeclarative.h -o moc_knotsdeclarative.cpp

moc_mainwindow.cpp: knotsplayer.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_knotsplayerproperties.cpp: knotsplayerproperties.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knotsplayerproperties.h -o moc_knotsplayerproperties.cpp

moc_knotsplayer.cpp: knotsplayer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knotsplayer.h -o moc_knotsplayer.cpp

moc_knotsitem.cpp: knotsitem.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knotsitem.h -o moc_knotsitem.cpp

moc_knotsdirectory.cpp: knotsitem.h \
		saxknotsitemhandler.h \
		knotsdirectory.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) knotsdirectory.h -o moc_knotsdirectory.cpp

compiler_rcc_make_all: qrc_qtknots.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtknots.cpp
qrc_qtknots.cpp: qtknots.qrc \
		qml/QKnots.qml \
		qml/common/Slider.qml \
		qml/common/OptionsPage.qml \
		qml/common/OptionsModel.qml \
		qml/common/VideoControls.qml \
		qml/common/DirectoryView.qml \
		qml/common/SearchView.qml \
		qml/common/ProfilesDelegate.qml \
		qml/common/ProfilesView.qml \
		qml/common/Progress.qml \
		qml/common/ToolBar.qml \
		qml/common/PlayingView.qml \
		qml/common/scrollbar.qml \
		qml/common/Button.qml \
		qml/common/GridDelegate.qml \
		qml/common/TitleBar.qml \
		qml/common/Directory.qml \
		qml/common/GridView.qml \
		qml/common/OptionsView.qml \
		qml/common/DirectoryDelegate.qml \
		qml/images/menu-toolbar.png \
		qml/images/knots_button_search.png \
		qml/images/Makefile.am \
		qml/images/scroll-hbackground.png \
		qml/images/scroll-vhandle.png \
		qml/images/pathbar-button-last-active.png \
		qml/images/close-hover.png \
		qml/images/expander-arrow-down-hover.png \
		qml/images/icon-m-toolbar-list.svg \
		qml/images/knots_dir.png \
		qml/images/knots_button_prev.png \
		qml/images/combobox-marker.png \
		qml/images/button-hover.png \
		qml/images/knots_button_rate.png \
		qml/images/wmCloseIconPressed.png \
		qml/images/titlebar.png \
		qml/images/scroll-vhandle-hover.png \
		qml/images/knots_button_play_artist.png \
		qml/images/expander-arrow-up.png \
		qml/images/knots_button_save_as.png \
		qml/images/plus-button-checked-hover.png \
		qml/images/scroll-hhandle-disabled.png \
		qml/images/slider-background.png \
		qml/images/toolbutton.png \
		qml/images/scroll-hhandle-hover.png \
		qml/images/scroll-button-left.png \
		qml/images/scroll-button-right-hover.png \
		qml/images/close.png \
		qml/images/knots_item_video.png \
		qml/images/pathbar-button.png \
		qml/images/toolbutton.sci \
		qml/images/combobox.png \
		qml/images/default.css \
		qml/images/toggle-background-active.png \
		qml/images/edit-find.png \
		qml/images/titlebar.sci \
		qml/images/scroll-vhandle-active.png \
		qml/images/toggle-handle.png \
		qml/images/scroll-button-left-hover.png \
		qml/images/scroll-hhandle-active.png \
		qml/images/plus-button.png \
		qml/images/expander-open.png \
		qml/images/knots_button_stop.png \
		qml/images/icon-m-toolbar-grid.svg \
		qml/images/slider-handle.png \
		qml/images/knots_item_server.png \
		qml/images/menu-item.png \
		qml/images/expander-arrow-down.png \
		qml/images/knots_button_next.png \
		qml/images/tooltip-background.png \
		qml/images/combobox-toolbar-marker.png \
		qml/images/wmCloseIcon.png \
		qml/images/knots_button_playlist.png \
		qml/images/plus-button-hover.png \
		qml/images/wmTaskSwitcherIcon.png \
		qml/images/scroll-hbackground-disabled.png \
		qml/images/toggle-background.png \
		qml/images/slider-background-hover.png \
		qml/images/knots_item_music.png \
		qml/images/lineedit.sci \
		qml/images/scroll-button-down.png \
		qml/images/slider-handle-hover.png \
		qml/images/slider-handle-active.png \
		qml/images/pathbar-button-active.png \
		qml/images/pathbar-button-focus.png \
		qml/images/toolbar-button-hover.png \
		qml/images/lineedit.png \
		qml/images/pathbar-button-last-hover.png \
		qml/images/plus-button-checked.png \
		qml/images/pathbar-button-last-focus.png \
		qml/images/scroll-vbackground.png \
		qml/images/menu.png \
		qml/images/knots_button_repeat.png \
		qml/images/knots_button_info.png \
		qml/images/pathbar-button-last.png \
		qml/images/knots_button_lyrics.png \
		qml/images/quit.png \
		qml/images/gloss.png \
		qml/images/knots_button_remove_from_playlist.png \
		qml/images/slider-background-disabled.png \
		qml/images/knots_button_back.png \
		qml/images/pathbar-button-hover.png \
		qml/images/expander-arrow-up-hover.png \
		qml/images/knots_button_no_repeat.png \
		qml/images/progress-bar-background.png \
		qml/images/slider-background-active.png \
		qml/images/knots_item_connect.png \
		qml/images/slider-handle-disabled.png \
		qml/images/knots_button_play.png \
		qml/images/knots_button_next_item.png \
		qml/images/expander-closed.png \
		qml/images/scroll-button-right.png \
		qml/images/knots_button_add_to_playlist.png \
		qml/images/slider-background-focus.png \
		qml/images/button.png \
		qml/images/scroll-button-up-hover.png \
		qml/images/scroll-vbackground-disabled.png \
		qml/images/scroll-button-down-hover.png \
		qml/images/expander-hover.png \
		qml/images/scroll-button-up.png \
		qml/images/resize-grip.png \
		qml/images/slider-handle-focus.png \
		qml/images/knots_button_new.png \
		qml/images/progress-bar-bar.png \
		qml/images/wmTaskSwitcherIconPressed.png \
		qml/images/entry-active.png \
		qml/images/knots_button_play_album.png \
		qml/images/knots_button_delete.png \
		qml/images/edit-clear.png \
		qml/images/combobox-toolbar.png \
		qml/images/knots_button_reorder.png \
		qml/images/scroll-hhandle.png \
		qml/images/scroll-vhandle-disabled.png \
		qml/images/entry.png \
		qml/images/knots_button_clear_position.png \
		qml/images/knots_button_player.png \
		qml/images/knots2.png \
		qml/images/stripes.png \
		qml/images/button-active.png \
		qml/images/mediaplayer/AppletBack.png \
		qml/images/mediaplayer/Repeat.png \
		qml/images/mediaplayer/VideoOverlayButton.png \
		qml/images/mediaplayer/Button.png \
		qml/images/mediaplayer/AppletPause.png \
		qml/images/mediaplayer/AppletForward.png \
		qml/images/mediaplayer/Play.png \
		qml/images/mediaplayer/Back.png \
		qml/images/mediaplayer/background.png \
		qml/images/mediaplayer/Shuffle.png \
		qml/images/mediaplayer/Crossfade.png \
		qml/images/mediaplayer/Forward.png \
		qml/images/mediaplayer/BackPressed.png \
		qml/images/mediaplayer/ShufflePressed.png \
		qml/images/mediaplayer/AppletStop.png \
		qml/images/mediaplayer/CrossfadePressed.png \
		qml/images/mediaplayer/Stop.png \
		qml/images/mediaplayer/ForwardPressed.png \
		qml/images/mediaplayer/AppletPlay.png \
		qml/images/mediaplayer/Pause.png \
		qml/images/mediaplayer/StopPressed.png \
		qml/images/mediaplayer/RepeatPressed.png \
		qml/images/mediaplayer/VideoOverlayButtonPressed.png
	/usr/bin/rcc -name qtknots qtknots.qrc -o qrc_qtknots.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp knots.h \
		profile.h \
		mainwindow.h \
		knotsplayer.h \
		knotsdirectory.h \
		knotsitem.h \
		saxknotsitemhandler.h \
		knotsdeclarative.h \
		knotsplayerproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

knots.o: knots.cpp knots.h \
		profile.h \
		mainwindow.h \
		knotsplayer.h \
		saxprofilehandler.h \
		knotsdirectory.h \
		knotsitem.h \
		saxknotsitemhandler.h \
		knotsdeclarative.h \
		knotsplayerproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knots.o knots.cpp

profile.o: profile.cpp profile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profile.o profile.cpp

saxprofilehandler.o: saxprofilehandler.cpp saxprofilehandler.h \
		profile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saxprofilehandler.o saxprofilehandler.cpp

knotsdeclarative.o: knotsdeclarative.cpp knotsdeclarative.h \
		profile.h \
		knotsdirectory.h \
		knotsitem.h \
		saxknotsitemhandler.h \
		knotsplayerproperties.h \
		knots.h \
		mainwindow.h \
		knotsplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotsdeclarative.o knotsdeclarative.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		knotsplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

knotsplayerproperties.o: knotsplayerproperties.cpp knots.h \
		profile.h \
		mainwindow.h \
		knotsplayer.h \
		knotsplayerproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotsplayerproperties.o knotsplayerproperties.cpp

knotsplayer.o: knotsplayer.cpp knotsplayer.h \
		knots.h \
		profile.h \
		mainwindow.h \
		knotsplayerproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotsplayer.o knotsplayer.cpp

knotsitem.o: knotsitem.cpp knots.h \
		profile.h \
		mainwindow.h \
		knotsplayer.h \
		knotsitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotsitem.o knotsitem.cpp

knotsdirectory.o: knotsdirectory.cpp knotsdirectory.h \
		knotsitem.h \
		saxknotsitemhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knotsdirectory.o knotsdirectory.cpp

saxknotsitemhandler.o: saxknotsitemhandler.cpp saxknotsitemhandler.h \
		knotsitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saxknotsitemhandler.o saxknotsitemhandler.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

moc_knots.o: moc_knots.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knots.o moc_knots.cpp

moc_profile.o: moc_profile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profile.o moc_profile.cpp

moc_knotsdeclarative.o: moc_knotsdeclarative.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotsdeclarative.o moc_knotsdeclarative.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_knotsplayerproperties.o: moc_knotsplayerproperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotsplayerproperties.o moc_knotsplayerproperties.cpp

moc_knotsplayer.o: moc_knotsplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotsplayer.o moc_knotsplayer.cpp

moc_knotsitem.o: moc_knotsitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotsitem.o moc_knotsitem.cpp

moc_knotsdirectory.o: moc_knotsdirectory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knotsdirectory.o moc_knotsdirectory.cpp

qrc_qtknots.o: qrc_qtknots.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtknots.o qrc_qtknots.cpp

####### Install

install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /scratchbox/users/andy/home/andy/qtknots/qtknots.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qtknots.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 
	-$(INSTALL_FILE) /scratchbox/users/andy/home/andy/qtknots/qtknots.png $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/qtknots.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install:  install_desktopfile install_icon install_target  FORCE

uninstall: uninstall_desktopfile uninstall_icon uninstall_target   FORCE

FORCE:

