#############################################################################
# Makefile for building: qtknots
# Generated by qmake (2.01a) (Qt 4.7.1) on: Thu 23. Dec 11:53:23 2010
# Project:  qtknots.pro
# Template: app
# Command: c:\qt\4.7.0-git\bin\qmake.exe -spec ..\..\4.7.0-git\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\qt\4.7.0-git\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: qtknots.pro  ..\..\4.7.0-git\mkspecs\win32-msvc2008\qmake.conf ..\..\4.7.0-git\mkspecs\qconfig.pri \
		..\..\4.7.0-git\mkspecs\modules\qt_webkit_version.pri \
		..\..\4.7.0-git\mkspecs\features\qt_functions.prf \
		..\..\4.7.0-git\mkspecs\features\qt_config.prf \
		..\..\4.7.0-git\mkspecs\features\exclusive_builds.prf \
		..\..\4.7.0-git\mkspecs\features\default_pre.prf \
		..\..\4.7.0-git\mkspecs\features\win32\default_pre.prf \
		qmlapplicationviewer\qmlapplicationviewer.pri \
		models\models.pri \
		kernel\kernel.pri \
		..\..\4.7.0-git\mkspecs\features\debug.prf \
		..\..\4.7.0-git\mkspecs\features\debug_and_release.prf \
		..\..\4.7.0-git\mkspecs\features\default_post.prf \
		..\..\4.7.0-git\mkspecs\features\win32\default_post.prf \
		..\..\4.7.0-git\mkspecs\features\win32\rtti.prf \
		..\..\4.7.0-git\mkspecs\features\win32\exceptions.prf \
		..\..\4.7.0-git\mkspecs\features\win32\stl.prf \
		..\..\4.7.0-git\mkspecs\features\win32\msvc_mp.prf \
		..\..\4.7.0-git\mkspecs\features\shared.prf \
		..\..\4.7.0-git\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\4.7.0-git\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\4.7.0-git\mkspecs\features\warn_on.prf \
		..\..\4.7.0-git\mkspecs\features\qt.prf \
		..\..\4.7.0-git\mkspecs\features\win32\opengl.prf \
		..\..\4.7.0-git\mkspecs\features\win32\thread.prf \
		..\..\4.7.0-git\mkspecs\features\moc.prf \
		..\..\4.7.0-git\mkspecs\features\win32\windows.prf \
		..\..\4.7.0-git\mkspecs\features\resources.prf \
		..\..\4.7.0-git\mkspecs\features\uic.prf \
		..\..\4.7.0-git\mkspecs\features\yacc.prf \
		..\..\4.7.0-git\mkspecs\features\lex.prf \
		..\..\4.7.0-git\mkspecs\features\include_source_dir.prf \
		c:\Qt\4.7.0-git\lib\qtmaind.prl
	$(QMAKE) -spec ..\..\4.7.0-git\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro
..\..\4.7.0-git\mkspecs\qconfig.pri:
..\..\4.7.0-git\mkspecs\modules\qt_webkit_version.pri:
..\..\4.7.0-git\mkspecs\features\qt_functions.prf:
..\..\4.7.0-git\mkspecs\features\qt_config.prf:
..\..\4.7.0-git\mkspecs\features\exclusive_builds.prf:
..\..\4.7.0-git\mkspecs\features\default_pre.prf:
..\..\4.7.0-git\mkspecs\features\win32\default_pre.prf:
qmlapplicationviewer\qmlapplicationviewer.pri:
models\models.pri:
kernel\kernel.pri:
..\..\4.7.0-git\mkspecs\features\debug.prf:
..\..\4.7.0-git\mkspecs\features\debug_and_release.prf:
..\..\4.7.0-git\mkspecs\features\default_post.prf:
..\..\4.7.0-git\mkspecs\features\win32\default_post.prf:
..\..\4.7.0-git\mkspecs\features\win32\rtti.prf:
..\..\4.7.0-git\mkspecs\features\win32\exceptions.prf:
..\..\4.7.0-git\mkspecs\features\win32\stl.prf:
..\..\4.7.0-git\mkspecs\features\win32\msvc_mp.prf:
..\..\4.7.0-git\mkspecs\features\shared.prf:
..\..\4.7.0-git\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\4.7.0-git\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\4.7.0-git\mkspecs\features\warn_on.prf:
..\..\4.7.0-git\mkspecs\features\qt.prf:
..\..\4.7.0-git\mkspecs\features\win32\opengl.prf:
..\..\4.7.0-git\mkspecs\features\win32\thread.prf:
..\..\4.7.0-git\mkspecs\features\moc.prf:
..\..\4.7.0-git\mkspecs\features\win32\windows.prf:
..\..\4.7.0-git\mkspecs\features\resources.prf:
..\..\4.7.0-git\mkspecs\features\uic.prf:
..\..\4.7.0-git\mkspecs\features\yacc.prf:
..\..\4.7.0-git\mkspecs\features\lex.prf:
..\..\4.7.0-git\mkspecs\features\include_source_dir.prf:
c:\Qt\4.7.0-git\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\4.7.0-git\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=C:/Qt/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile qtknots.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) ".\qtknots.intermediate.manifest"
	-$(DEL_FILE) qtknots.exp
	-$(DEL_FILE) qtknots.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) qtknots.pdb

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
